version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: thefactory-db-postgres
    environment:
      POSTGRES_DB: thefactory-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
